version: "2"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/martincostello/advent-of-go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: standard
  enable:
    - gocritic
    - misspell
    - unconvert
    - unused
